# RawNet model configuration for network packet anomaly detection

# Training parameters
optimizer: 'adam'
lr: 0.0001
weight_decay: 0.0001
nb_epochs: 10
batch_size: 32
early_stopping: 10

# Model architecture
in_channels: 1
first_conv: 1024
filts: [[128, 128], [128, 128], [128, 128]]
gru_node: 1024
nb_gru_layer: 2
nb_fc_node: 1024
nb_classes: 2  # Binary classification: normal vs anomaly

# Data parameters
max_packet_length: 1500  # Maximum Ethernet packet size
sample_rate: 1000  # Sampling rate for network packets 